require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProductVersionsController do

  def mock_product_version(stubs={})
    @mock_product_version ||= mock_model(ProductVersion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all product_versions as @product_versions" do
      ProductVersion.stub(:all) { [mock_product_version] }
      get :index
      assigns(:product_versions).should eq([mock_product_version])
    end
  end

  describe "GET show" do
    it "assigns the requested product_version as @product_version" do
      ProductVersion.stub(:find).with("37") { mock_product_version }
      get :show, :id => "37"
      assigns(:product_version).should be(mock_product_version)
    end
  end

  describe "GET new" do
    it "assigns a new product_version as @product_version" do
      ProductVersion.stub(:new) { mock_product_version }
      get :new
      assigns(:product_version).should be(mock_product_version)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_version as @product_version" do
      ProductVersion.stub(:find).with("37") { mock_product_version }
      get :edit, :id => "37"
      assigns(:product_version).should be(mock_product_version)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created product_version as @product_version" do
        ProductVersion.stub(:new).with({'these' => 'params'}) { mock_product_version(:save => true) }
        post :create, :product_version => {'these' => 'params'}
        assigns(:product_version).should be(mock_product_version)
      end

      it "redirects to the created product_version" do
        ProductVersion.stub(:new) { mock_product_version(:save => true) }
        post :create, :product_version => {}
        response.should redirect_to(product_version_url(mock_product_version))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_version as @product_version" do
        ProductVersion.stub(:new).with({'these' => 'params'}) { mock_product_version(:save => false) }
        post :create, :product_version => {'these' => 'params'}
        assigns(:product_version).should be(mock_product_version)
      end

      it "re-renders the 'new' template" do
        ProductVersion.stub(:new) { mock_product_version(:save => false) }
        post :create, :product_version => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_version" do
        ProductVersion.stub(:find).with("37") { mock_product_version }
        mock_product_version.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :product_version => {'these' => 'params'}
      end

      it "assigns the requested product_version as @product_version" do
        ProductVersion.stub(:find) { mock_product_version(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:product_version).should be(mock_product_version)
      end

      it "redirects to the product_version" do
        ProductVersion.stub(:find) { mock_product_version(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(product_version_url(mock_product_version))
      end
    end

    describe "with invalid params" do
      it "assigns the product_version as @product_version" do
        ProductVersion.stub(:find) { mock_product_version(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:product_version).should be(mock_product_version)
      end

      it "re-renders the 'edit' template" do
        ProductVersion.stub(:find) { mock_product_version(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_version" do
      ProductVersion.stub(:find).with("37") { mock_product_version }
      mock_product_version.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the product_versions list" do
      ProductVersion.stub(:find) { mock_product_version }
      delete :destroy, :id => "1"
      response.should redirect_to(product_versions_url)
    end
  end

end
